<a href="https://colab.research.google.com/github/nastynoice/test/blob/main/Practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1)
print("List of months: January, February, March, April, May, June, July, August, September, October, November, December")
month_name = input("Input the name of Month: ")

if month_name == "February":
	print("No. of days: 28/29 days")
elif month_name in ("April", "June", "September", "November"):
	print("No. of days: 30 days")
elif month_name in ("January", "March", "May", "July", "August", "October", "December"):
	print("No. of days: 31 day")
else:
	print("Wrong month name") 

List of months: January, February, March, April, May, June, July, August, September, October, November, December
Input the name of Month: st
Wrong month name


In [ ]:
user_input = input('Enter word sequence:')

string = user_input.split()

temp = [i[::-1] for i in string]

unique = 0
is_palindrome = 0

for i in range(len(temp)):
    if temp[i] == string[i]:
        is_palindrome += 1
    else:
        unique += 1

print('There are', is_palindrome, 'Palindromes, and', unique, 'unique words')

Enter word sequence:abba 1234 1331
There are 2 Palindromes, and 1 unique words


In [ ]:
#Q2)
string=input(("Enter a string:"))
if(string==string[::-1]):
      print("The string is a palindrome")
else:
      print("Not a palindrome")

Enter a string:aba
The string is a palindrome


In [ ]:
#Q3)
def last(n): return n[-1]

def sort_list_last(tuples):
  return sorted(tuples, key=last)

print(sort_list_last([(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]))

[(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]


In [ ]:
#Q4)
from itertools import product

d ={'1':['a','b'], '2':['c','d']}

for x, y in product(*d.values()):
    print(x + y)

ac
ad
bc
bd


In [ ]:
#Q5)
t = (100, 200, 300)
print(format(t))
#https://www.w3resource.com/python-exercises/tuple/python-tuple-exercise-20.php

(100, 200, 300)


In [ ]:
#Q6)
class py_solution:
   def is_valid_parenthese(self, str1):
        stack, pchar = [], {"(": ")", "{": "}", "[": "]"}
        for parenthese in str1:
            if parenthese in pchar:
                stack.append(parenthese)
            elif len(stack) == 0 or pchar[stack.pop()] != parenthese:
                return False
        return len(stack) == 0

print(py_solution().is_valid_parenthese("(){}[]"))
print(py_solution().is_valid_parenthese("()[{)}"))
print(py_solution().is_valid_parenthese("()"))
#https://www.w3resource.com/python-exercises/class-exercises/python-class-exercise-3.php

True
False
True


In [ ]:
#8) Objective: Write a program to implement PCA.
# Principal Component Analysis is a method for reducing
# the dimensionality of data. A projection method where
# data with m-columns (features) is project into a subspace 
#with new eigen - vectors as new axis whilst retaining 
#essence of original data
# Algorithm:
#       1) Calculate mean values of each columns/feature
#      # 2) Center or normalize the values by subtracting mean column value
#       3) calculate covariance matrix of the centered matrix(C)
#        Correlation is a normalized measure of the amount and 
#        direction (positive or negative) that two columns change 
#        together. Covariance is a generalized and unnormalized 
#        version of correlation across multiple columns. 
#        A covariance matrix is a calculation of covariance of a 
#        given matrix with covariance scores for
#         every column with every other column, including itself

        #  4) perform eigen-decomposition of cov matrix resulting
        #  eigen vectors and values.
        #  The eigenvectors represent the directions or 
        #  components for the reduced subspace of B,
        #   whereas the eigenvalues
        #   represent the magnitudes for the directions

from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
print("define a matrix")
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
print ("calculate the mean of each column")
M = mean(A.T, axis=1)
print(M)
print ("center columns by subtracting column means")
C = A - M
print(C)
print("calculate covariance matrix of centered matrix")
V = cov(C.T)
print(V)
print("eigendecomposition of covariance matrix")
values, vectors = eig(V)
print("Eigen-Vector:")
print(vectors)
print("Eigen-Values:")
print(values)
print("project data")
P = vectors.T.dot(C.T)
print(P.T)



define a matrix
[[1 2]
 [3 4]
 [5 6]]
calculate the mean of each column
[3. 4.]
center columns by subtracting column means
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]
calculate covariance matrix of centered matrix
[[4. 4.]
 [4. 4.]]
eigendecomposition of covariance matrix
Eigen-Vector:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Eigen-Values:
[8. 0.]
project data
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


In [ ]:
# only 1st eigen vector is required to analyse data,
#we can project our 3*2 matrix onto 3*1

In [ ]:
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      // Resize the output to fit the video element.
      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Wait for Capture to be clicked.
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  display(js)
  data = eval_js('takePhoto({})'.format(quality))
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename

In [ ]:
from IPython.display import Image
try:
  filename = take_photo()
  print('Saved to {}'.format(filename))
  
  # Show the image which was just taken.
  display(Image(filename))
except Exception as err:
  # Errors will be thrown if the user does not have a webcam or if they do not
  # grant the page permission to access it.
  print(str(err))